spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/tmall_pms?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  banner:
    location: banner.txt
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: tmall-product
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: localhost
    password: tym917
  session:
    store-type: redis



mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

  

server:
  port: 8004
logging:
  level:
    com.tym.Tmall: debug
